// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlM1dpuie7IIYJAQ-DIQIaCTZ8aT5oArQ',
    appId: '1:385640430265:web:e4adb78eef5b4ad91f7968',
    messagingSenderId: '385640430265',
    projectId: 'time-scheduler-app-35399',
    authDomain: 'time-scheduler-app-35399.firebaseapp.com',
    storageBucket: 'time-scheduler-app-35399.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCVAoOwZCNULgKbQGyKChXl8Zd5XN9jCk',
    appId: '1:385640430265:android:5d70ff133072019d1f7968',
    messagingSenderId: '385640430265',
    projectId: 'time-scheduler-app-35399',
    storageBucket: 'time-scheduler-app-35399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQSVQZ01YQJoAJsu-n-832IrTqfvi46w4',
    appId: '1:385640430265:ios:39876132d45bd4f11f7968',
    messagingSenderId: '385640430265',
    projectId: 'time-scheduler-app-35399',
    storageBucket: 'time-scheduler-app-35399.appspot.com',
    iosBundleId: 'com.example.timeScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQSVQZ01YQJoAJsu-n-832IrTqfvi46w4',
    appId: '1:385640430265:ios:39876132d45bd4f11f7968',
    messagingSenderId: '385640430265',
    projectId: 'time-scheduler-app-35399',
    storageBucket: 'time-scheduler-app-35399.appspot.com',
    iosBundleId: 'com.example.timeScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlM1dpuie7IIYJAQ-DIQIaCTZ8aT5oArQ',
    appId: '1:385640430265:web:c1d4bebc1c86d2ea1f7968',
    messagingSenderId: '385640430265',
    projectId: 'time-scheduler-app-35399',
    authDomain: 'time-scheduler-app-35399.firebaseapp.com',
    storageBucket: 'time-scheduler-app-35399.appspot.com',
  );
}
